version: '3.8'

services:
  spark-container:
    image: jupyter/pyspark-notebook
    container_name: spark-container
    ports:
      - "8888:8888"
      - "4040:4040"
      - "7077:7077"
    volumes:
      - .:/home/jovyan/work